syntax = "proto3";

package io.github.nightfuryar.springbootgrpcdemo.proto.locationtracker.v1;

option java_multiple_files = true;
option java_package = "io.github.nightfuryar.springbootgrpcdemo.locationtracker.v1";
option java_outer_classname = "LocationTrackerPayloadProto";

message VehicleRegistrationRequest {
  double vehicle_id = 1; // unique identifier for the vehicle
  string vehicle_number = 2; // here vehicle id is vehicle number
  string vehicle_type = 3;
  string owner_name = 4;
}

message VehicleRegistrationResponse {
  double vehicle_id = 1;
  string vehicle_number = 2;
  string status = 3; // e.g., "registered", "already_exists"
}

message VehicleLocation {
  double vehicle_id = 1; // unique identifier for the vehicle
  string vehicle_number = 2;
  double latitude = 3;
  double longitude = 4;
  int64 timestamp = 5;
}

message VehicleLocationHistoryRequest {
  string vehicle_number = 1;
}

message LocationUploadStatus {
  int32 total_received = 1;
  string status = 2;
}

message LocationAcknowledgement {
  string message = 1;
}