syntax = "proto3";

package io.github.nightfuryar.springbootgrpcdemo.proto.locationtracker.v1;

option java_multiple_files = true;
option java_package = "io.github.nightfuryar.springbootgrpcdemo.locationtracker.v1";
option java_outer_classname = "LocationTrackerPayloadProto";

message VehicleRegistrationRequest {
  string vehicle_id = 1;
  string vehicle_type = 2;
  string owner_name = 3;
}

message VehicleRegistrationResponse {
  string vehicle_id = 1;
  string status = 2; // e.g., "registered", "already_exists"
}

message VehicleLocation {
  string vehicle_id = 1;
  double latitude = 2;
  double longitude = 3;
  int64 timestamp = 4;
}

message VehicleLocationHistoryRequest {
  string vehicle_id = 1;
}

message LocationUploadStatus {
  int32 total_received = 1;
  string status = 2;
}

message LocationAcknowledgement {
  string message = 1;
}